/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class danger_states_lcmt implements lcm.lcm.LCMEncodable
{
    public float motor_temperature[];
 
    public danger_states_lcmt()
    {
        motor_temperature = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1c19f0fc56472aa4L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.danger_states_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.danger_states_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.motor_temperature[a]); 
        }
 
    }
 
    public danger_states_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public danger_states_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.danger_states_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.danger_states_lcmt o = new lcmtypes.danger_states_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.motor_temperature = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.motor_temperature[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.danger_states_lcmt copy()
    {
        lcmtypes.danger_states_lcmt outobj = new lcmtypes.danger_states_lcmt();
        outobj.motor_temperature = new float[(int) 12];
        System.arraycopy(this.motor_temperature, 0, outobj.motor_temperature, 0, 12); 
        return outobj;
    }
 
}

