/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class error_flag_lcmt implements lcm.lcm.LCMEncodable
{
    public byte exist_error;
    public byte ori_error;
    public int footpos_error;
    public int motor_error[];
 
    public error_flag_lcmt()
    {
        motor_error = new int[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8779d473df5369b8L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.error_flag_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.error_flag_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.exist_error); 
 
        outs.writeByte(this.ori_error); 
 
        outs.writeInt(this.footpos_error); 
 
        for (int a = 0; a < 12; a++) {
            outs.writeInt(this.motor_error[a]); 
        }
 
    }
 
    public error_flag_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public error_flag_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.error_flag_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.error_flag_lcmt o = new lcmtypes.error_flag_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.exist_error = ins.readByte();
 
        this.ori_error = ins.readByte();
 
        this.footpos_error = ins.readInt();
 
        this.motor_error = new int[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.motor_error[a] = ins.readInt();
        }
 
    }
 
    public lcmtypes.error_flag_lcmt copy()
    {
        lcmtypes.error_flag_lcmt outobj = new lcmtypes.error_flag_lcmt();
        outobj.exist_error = this.exist_error;
 
        outobj.ori_error = this.ori_error;
 
        outobj.footpos_error = this.footpos_error;
 
        outobj.motor_error = new int[(int) 12];
        System.arraycopy(this.motor_error, 0, outobj.motor_error, 0, 12); 
        return outobj;
    }
 
}

