/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class file_recv_lcmt implements lcm.lcm.LCMEncodable
{
    public byte result;
 
    public file_recv_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf676533f1f6d36beL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.file_recv_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.file_recv_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.result); 
 
    }
 
    public file_recv_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public file_recv_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.file_recv_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.file_recv_lcmt o = new lcmtypes.file_recv_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.result = ins.readByte();
 
    }
 
    public lcmtypes.file_recv_lcmt copy()
    {
        lcmtypes.file_recv_lcmt outobj = new lcmtypes.file_recv_lcmt();
        outobj.result = this.result;
 
        return outobj;
    }
 
}

