/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class leg_control_data_lcmt implements lcm.lcm.LCMEncodable
{
    public float q[];
    public float qd[];
    public float p[];
    public float v[];
    public float tau_est[];
    public float force_est[];
    public float force_desired[];
    public int q_abad_limit[];
    public int q_hip_limit[];
    public int q_knee_limit[];
 
    public leg_control_data_lcmt()
    {
        q = new float[12];
        qd = new float[12];
        p = new float[12];
        v = new float[12];
        tau_est = new float[12];
        force_est = new float[12];
        force_desired = new float[12];
        q_abad_limit = new int[4];
        q_hip_limit = new int[4];
        q_knee_limit = new int[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa6b1824464a42a6bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.leg_control_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.leg_control_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.q[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.qd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.p[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.v[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.tau_est[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.force_est[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.force_desired[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeInt(this.q_abad_limit[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeInt(this.q_hip_limit[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeInt(this.q_knee_limit[a]); 
        }
 
    }
 
    public leg_control_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public leg_control_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.leg_control_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.leg_control_data_lcmt o = new lcmtypes.leg_control_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.q = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.q[a] = ins.readFloat();
        }
 
        this.qd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.qd[a] = ins.readFloat();
        }
 
        this.p = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.p[a] = ins.readFloat();
        }
 
        this.v = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.v[a] = ins.readFloat();
        }
 
        this.tau_est = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.tau_est[a] = ins.readFloat();
        }
 
        this.force_est = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.force_est[a] = ins.readFloat();
        }
 
        this.force_desired = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.force_desired[a] = ins.readFloat();
        }
 
        this.q_abad_limit = new int[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.q_abad_limit[a] = ins.readInt();
        }
 
        this.q_hip_limit = new int[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.q_hip_limit[a] = ins.readInt();
        }
 
        this.q_knee_limit = new int[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.q_knee_limit[a] = ins.readInt();
        }
 
    }
 
    public lcmtypes.leg_control_data_lcmt copy()
    {
        lcmtypes.leg_control_data_lcmt outobj = new lcmtypes.leg_control_data_lcmt();
        outobj.q = new float[(int) 12];
        System.arraycopy(this.q, 0, outobj.q, 0, 12); 
        outobj.qd = new float[(int) 12];
        System.arraycopy(this.qd, 0, outobj.qd, 0, 12); 
        outobj.p = new float[(int) 12];
        System.arraycopy(this.p, 0, outobj.p, 0, 12); 
        outobj.v = new float[(int) 12];
        System.arraycopy(this.v, 0, outobj.v, 0, 12); 
        outobj.tau_est = new float[(int) 12];
        System.arraycopy(this.tau_est, 0, outobj.tau_est, 0, 12); 
        outobj.force_est = new float[(int) 12];
        System.arraycopy(this.force_est, 0, outobj.force_est, 0, 12); 
        outobj.force_desired = new float[(int) 12];
        System.arraycopy(this.force_desired, 0, outobj.force_desired, 0, 12); 
        outobj.q_abad_limit = new int[(int) 4];
        System.arraycopy(this.q_abad_limit, 0, outobj.q_abad_limit, 0, 4); 
        outobj.q_hip_limit = new int[(int) 4];
        System.arraycopy(this.q_hip_limit, 0, outobj.q_hip_limit, 0, 4); 
        outobj.q_knee_limit = new int[(int) 4];
        System.arraycopy(this.q_knee_limit, 0, outobj.q_knee_limit, 0, 4); 
        return outobj;
    }
 
}

