/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motion_control_command_lcmt implements lcm.lcm.LCMEncodable
{
    public int mode;
    public int gait_id;
    public float x_vel_des;
    public float y_vel_des;
    public float yaw_vel_des;
    public float rpy_des[];
    public float body_height;
    public float step_height;
    public int order;
 
    public motion_control_command_lcmt()
    {
        rpy_des = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xbd18999dbfbc5ce5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.motion_control_command_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.motion_control_command_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.mode); 
 
        outs.writeInt(this.gait_id); 
 
        outs.writeFloat(this.x_vel_des); 
 
        outs.writeFloat(this.y_vel_des); 
 
        outs.writeFloat(this.yaw_vel_des); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy_des[a]); 
        }
 
        outs.writeFloat(this.body_height); 
 
        outs.writeFloat(this.step_height); 
 
        outs.writeInt(this.order); 
 
    }
 
    public motion_control_command_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motion_control_command_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.motion_control_command_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.motion_control_command_lcmt o = new lcmtypes.motion_control_command_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.mode = ins.readInt();
 
        this.gait_id = ins.readInt();
 
        this.x_vel_des = ins.readFloat();
 
        this.y_vel_des = ins.readFloat();
 
        this.yaw_vel_des = ins.readFloat();
 
        this.rpy_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy_des[a] = ins.readFloat();
        }
 
        this.body_height = ins.readFloat();
 
        this.step_height = ins.readFloat();
 
        this.order = ins.readInt();
 
    }
 
    public lcmtypes.motion_control_command_lcmt copy()
    {
        lcmtypes.motion_control_command_lcmt outobj = new lcmtypes.motion_control_command_lcmt();
        outobj.mode = this.mode;
 
        outobj.gait_id = this.gait_id;
 
        outobj.x_vel_des = this.x_vel_des;
 
        outobj.y_vel_des = this.y_vel_des;
 
        outobj.yaw_vel_des = this.yaw_vel_des;
 
        outobj.rpy_des = new float[(int) 3];
        System.arraycopy(this.rpy_des, 0, outobj.rpy_des, 0, 3); 
        outobj.body_height = this.body_height;
 
        outobj.step_height = this.step_height;
 
        outobj.order = this.order;
 
        return outobj;
    }
 
}

