/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motion_control_response_lcmt implements lcm.lcm.LCMEncodable
{
    public byte pattern;
    public byte order;
    public byte order_process_bar;
    public byte foot_contact;
    public lcmtypes.error_flag_lcmt error_flag;
 
    public motion_control_response_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7bea14505ededc35L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.motion_control_response_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.motion_control_response_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
             + lcmtypes.error_flag_lcmt._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.pattern); 
 
        outs.writeByte(this.order); 
 
        outs.writeByte(this.order_process_bar); 
 
        outs.writeByte(this.foot_contact); 
 
        this.error_flag._encodeRecursive(outs); 
 
    }
 
    public motion_control_response_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motion_control_response_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.motion_control_response_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.motion_control_response_lcmt o = new lcmtypes.motion_control_response_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.pattern = ins.readByte();
 
        this.order = ins.readByte();
 
        this.order_process_bar = ins.readByte();
 
        this.foot_contact = ins.readByte();
 
        this.error_flag = lcmtypes.error_flag_lcmt._decodeRecursiveFactory(ins);
 
    }
 
    public lcmtypes.motion_control_response_lcmt copy()
    {
        lcmtypes.motion_control_response_lcmt outobj = new lcmtypes.motion_control_response_lcmt();
        outobj.pattern = this.pattern;
 
        outobj.order = this.order;
 
        outobj.order_process_bar = this.order_process_bar;
 
        outobj.foot_contact = this.foot_contact;
 
        outobj.error_flag = this.error_flag.copy();
 
        return outobj;
    }
 
}

