/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motor_ctrl_state_lcmt implements lcm.lcm.LCMEncodable
{
    public short err_flag;
    public float ctrl_topic_interval;
 
    public motor_ctrl_state_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2afdf7bdf6035aeaL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.motor_ctrl_state_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.motor_ctrl_state_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeShort(this.err_flag); 
 
        outs.writeFloat(this.ctrl_topic_interval); 
 
    }
 
    public motor_ctrl_state_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motor_ctrl_state_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.motor_ctrl_state_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.motor_ctrl_state_lcmt o = new lcmtypes.motor_ctrl_state_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.err_flag = ins.readShort();
 
        this.ctrl_topic_interval = ins.readFloat();
 
    }
 
    public lcmtypes.motor_ctrl_state_lcmt copy()
    {
        lcmtypes.motor_ctrl_state_lcmt outobj = new lcmtypes.motor_ctrl_state_lcmt();
        outobj.err_flag = this.err_flag;
 
        outobj.ctrl_topic_interval = this.ctrl_topic_interval;
 
        return outobj;
    }
 
}

