/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motor_ctrl_lcmt implements lcm.lcm.LCMEncodable
{
    public float q_des[];
    public float qd_des[];
    public float kp_des[];
    public float kd_des[];
    public float tau_des[];
 
    public motor_ctrl_lcmt()
    {
        q_des = new float[12];
        qd_des = new float[12];
        kp_des = new float[12];
        kd_des = new float[12];
        tau_des = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3ddbe622bc22d656L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.motor_ctrl_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.motor_ctrl_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.q_des[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.qd_des[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.kp_des[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.kd_des[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.tau_des[a]); 
        }
 
    }
 
    public motor_ctrl_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motor_ctrl_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.motor_ctrl_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.motor_ctrl_lcmt o = new lcmtypes.motor_ctrl_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.q_des = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.q_des[a] = ins.readFloat();
        }
 
        this.qd_des = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.qd_des[a] = ins.readFloat();
        }
 
        this.kp_des = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.kp_des[a] = ins.readFloat();
        }
 
        this.kd_des = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.kd_des[a] = ins.readFloat();
        }
 
        this.tau_des = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.tau_des[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.motor_ctrl_lcmt copy()
    {
        lcmtypes.motor_ctrl_lcmt outobj = new lcmtypes.motor_ctrl_lcmt();
        outobj.q_des = new float[(int) 12];
        System.arraycopy(this.q_des, 0, outobj.q_des, 0, 12); 
        outobj.qd_des = new float[(int) 12];
        System.arraycopy(this.qd_des, 0, outobj.qd_des, 0, 12); 
        outobj.kp_des = new float[(int) 12];
        System.arraycopy(this.kp_des, 0, outobj.kp_des, 0, 12); 
        outobj.kd_des = new float[(int) 12];
        System.arraycopy(this.kd_des, 0, outobj.kd_des, 0, 12); 
        outobj.tau_des = new float[(int) 12];
        System.arraycopy(this.tau_des, 0, outobj.tau_des, 0, 12); 
        return outobj;
    }
 
}

