/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class new_bms_request_lcmt implements lcm.lcm.LCMEncodable
{
    public byte dest_id;
    public byte src_id;
    public byte lowpower_flag;
    public byte reserve;
 
    public new_bms_request_lcmt()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x47a0fa131e1d1b26L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.new_bms_request_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.new_bms_request_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte(this.dest_id); 
 
        outs.writeByte(this.src_id); 
 
        outs.writeByte(this.lowpower_flag); 
 
        outs.writeByte(this.reserve); 
 
    }
 
    public new_bms_request_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public new_bms_request_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.new_bms_request_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.new_bms_request_lcmt o = new lcmtypes.new_bms_request_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.dest_id = ins.readByte();
 
        this.src_id = ins.readByte();
 
        this.lowpower_flag = ins.readByte();
 
        this.reserve = ins.readByte();
 
    }
 
    public lcmtypes.new_bms_request_lcmt copy()
    {
        lcmtypes.new_bms_request_lcmt outobj = new lcmtypes.new_bms_request_lcmt();
        outobj.dest_id = this.dest_id;
 
        outobj.src_id = this.src_id;
 
        outobj.lowpower_flag = this.lowpower_flag;
 
        outobj.reserve = this.reserve;
 
        return outobj;
    }
 
}

