"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class bms_request_lcmt(object):
    __slots__ = ["charge_enable", "power_supply", "buzz", "locomotion_bits", "power_boards_bits", "other_bits"]

    __typenames__ = ["int8_t", "int8_t", "int8_t", "int8_t", "int8_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.charge_enable = 0
        self.power_supply = 0
        self.buzz = 0
        self.locomotion_bits = 0
        self.power_boards_bits = 0
        self.other_bits = 0

    def encode(self):
        buf = BytesIO()
        buf.write(bms_request_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbbbbb", self.charge_enable, self.power_supply, self.buzz, self.locomotion_bits, self.power_boards_bits, self.other_bits))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bms_request_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bms_request_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bms_request_lcmt()
        self.charge_enable, self.power_supply, self.buzz, self.locomotion_bits, self.power_boards_bits, self.other_bits = struct.unpack(">bbbbbb", buf.read(6))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if bms_request_lcmt in parents: return 0
        tmphash = (0x4de9e751782db678) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bms_request_lcmt._packed_fingerprint is None:
            bms_request_lcmt._packed_fingerprint = struct.pack(">Q", bms_request_lcmt._get_hash_recursive([]))
        return bms_request_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", bms_request_lcmt._get_packed_fingerprint())[0]

