"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class bms_response_lcmt(object):
    __slots__ = ["batt_volt", "batt_curr", "batt_temp", "batt_soc", "status", "key", "batt_health", "batt_loop_number", "powerBoard_status", "locomotion_bits", "power_boards_bits", "other_bits"]

    __typenames__ = ["int16_t", "int16_t", "int16_t", "int8_t", "int8_t", "int8_t", "int8_t", "int16_t", "int8_t", "int8_t", "int8_t", "int8_t"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.batt_volt = 0
        self.batt_curr = 0
        self.batt_temp = 0
        self.batt_soc = 0
        self.status = 0
        self.key = 0
        self.batt_health = 0
        self.batt_loop_number = 0
        self.powerBoard_status = 0
        self.locomotion_bits = 0
        self.power_boards_bits = 0
        self.other_bits = 0

    def encode(self):
        buf = BytesIO()
        buf.write(bms_response_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hhhbbbbhbbbb", self.batt_volt, self.batt_curr, self.batt_temp, self.batt_soc, self.status, self.key, self.batt_health, self.batt_loop_number, self.powerBoard_status, self.locomotion_bits, self.power_boards_bits, self.other_bits))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bms_response_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bms_response_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bms_response_lcmt()
        self.batt_volt, self.batt_curr, self.batt_temp, self.batt_soc, self.status, self.key, self.batt_health, self.batt_loop_number, self.powerBoard_status, self.locomotion_bits, self.power_boards_bits, self.other_bits = struct.unpack(">hhhbbbbhbbbb", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if bms_response_lcmt in parents: return 0
        tmphash = (0xdbb715bf65fdf256) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bms_response_lcmt._packed_fingerprint is None:
            bms_response_lcmt._packed_fingerprint = struct.pack(">Q", bms_response_lcmt._get_hash_recursive([]))
        return bms_response_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", bms_response_lcmt._get_packed_fingerprint())[0]

