"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class danger_states_lcmt(object):
    __slots__ = ["motor_temperature"]

    __typenames__ = ["float"]

    __dimensions__ = [[12]]

    def __init__(self):
        self.motor_temperature = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(danger_states_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12f', *self.motor_temperature[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != danger_states_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return danger_states_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = danger_states_lcmt()
        self.motor_temperature = struct.unpack('>12f', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if danger_states_lcmt in parents: return 0
        tmphash = (0x1c19f0fc56472aa4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if danger_states_lcmt._packed_fingerprint is None:
            danger_states_lcmt._packed_fingerprint = struct.pack(">Q", danger_states_lcmt._get_hash_recursive([]))
        return danger_states_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", danger_states_lcmt._get_packed_fingerprint())[0]

