"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class motor_ctrl_state_lcmt(object):
    __slots__ = ["err_flag", "ctrl_topic_interval"]

    __typenames__ = ["int16_t", "float"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.err_flag = 0
        self.ctrl_topic_interval = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(motor_ctrl_state_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hf", self.err_flag, self.ctrl_topic_interval))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_ctrl_state_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_ctrl_state_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = motor_ctrl_state_lcmt()
        self.err_flag, self.ctrl_topic_interval = struct.unpack(">hf", buf.read(6))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if motor_ctrl_state_lcmt in parents: return 0
        tmphash = (0x2afdf7bdf6035aea) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if motor_ctrl_state_lcmt._packed_fingerprint is None:
            motor_ctrl_state_lcmt._packed_fingerprint = struct.pack(">Q", motor_ctrl_state_lcmt._get_hash_recursive([]))
        return motor_ctrl_state_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", motor_ctrl_state_lcmt._get_packed_fingerprint())[0]

